### ISSUE TITLE
rsofun demo driver data 

### ISSUE THREAD

**Issue by stineb** [geco-bern/FluxDataKit#67]
I created a script to generate the rsofun demo driver data which we distribute through the rsofun package. It's in my fork under [`analysis/05_generate_demo_rsofun_drivers.R`](https://github.com/stineb/flux_data_kit/blob/main/analysis/05_generate_demo_rsofun_drivers.R).
I thought this was added to `geco-bern/FluxDataKit` through PR https://github.com/geco-bern/FluxDataKit/pull/60 (see [here](https://github.com/geco-bern/FluxDataKit/pull/60/files#diff-de6ef42858bd102f13d300a671acad422907bf83aa66439c60b9b95cd8594e33)). I also added a note in the README of `rsofun/data-raw`. Was it intentionally removed or not added here? I think we need it.

**Comment by khufkens** [comment]
Fixed
