### ISSUE TITLE
Add new data products - processing routine?

### ISSUE THREAD

**Issue by khufkens** [geco-bern/FluxDataKit#68]
- warm winter ICOS data
- double check some long running sites in the dataset - their origin and the picking order of the data

**Comment by stineb** [comment]
Here my code for determining "richest source" per site:
https://github.com/geco-bern/FluxDataKit/tree/add_sources/vignettes_tmp

**Comment by stineb** [comment]
It would be great to determine the source (among those listed by the vignette in the above link) with the longest available time series per site and use that for FDK. Now, it's implemented by a "global" source priority. For ICOS data, we should use the drought-2018 and warm-winter datasets (see links in vignetted above), not the one that is currently used for FDK as that is not a public release. Caveat: the years coverage determined in the vignette above is based on file names, not actually available data. Anyways, I would suggest to make the decision based on file names.
[See here for a html version of the vignette.](https://rpubs.com/stineb/fdk_additional_data_source)

**Comment by khufkens** [comment]
Data sources:

https://www.icos-cp.eu/data-products/2G60-ZHAK
https://www.icos-cp.eu/event/879

**Comment by stineb** [comment]
## Ameriflux

Downloaded data on 14 Oct 2023 from [https://ameriflux.lbl.gov/](https://ameriflux.lbl.gov/).


## ICOS Drought 2018

Data downloaded from [https://doi.org/10.18160/YVR0-4898](https://doi.org/10.18160/YVR0-4898).

## ICOS Warm Winter 2020

Data downloaded from [https://doi.org/10.18160/2G60-ZHAK](https://doi.org/10.18160/2G60-ZHAK)

**Comment by stineb** [comment]
Resolved by https://github.com/geco-bern/FluxDataKit/pull/72
