### ISSUE TITLE
Inconsistent IGBP types

### ISSUE THREAD

**Issue by jaideep777** [geco-bern/FluxDataKit#69]
The IGBP_veg_short field has inconsistent info, i.e., it sometimes has full forms fo the vegetation type and sometimes short forms. 

Proposed fix:

Use the following code (or something to that effect) to remap the full-forms while generating the NetCDF files
```
IGBP_veg_short = dplyr::case_match(IGBP_veg_short,
                                 "Woody Savannas" ~ "WSA",
                                 "Savannas" ~ "SAV",
                                 "Permanent Wetlands" ~ "WET",
                                 "Open Shrublands" ~ "OSH",
                                 "Closed Shrublands" ~ "CSH",
                                 "Grasslands" ~ "GRA",
                                 "Evergreen Needleleaf Forest" ~ "ENF",
                                 "Evergreen Broadleaf Forest" ~ "EBF",
                                 "Deciduous Broadleaf Forest" ~ "DBF",
                                 "Mixed Forest" ~ "MF",
                                 "Croplands" ~ "CRO",
                                 "Cropland/Natural Vegetation Mosaic" ~ "MF",
                                 "Urban and Built-Up" ~ NA,
                                 .default = IGBP_veg_short)
```

**Comment by stineb** [comment]
We have code in ingestr for preparing site-level meta data [here](https://github.com/geco-bern/ingestr/tree/master/data-raw). This may be adopted to solve this issue. It takes information from {amerifluxr} and from [Falge et al.](https://daac.ornl.gov/cgi-bin/dsviewer.pl?ds_id=1530). We don't need all of these meta info, but I recommend the following:

- Make sure to use IGBP vegetation type provided as meta-info for the site (available through {ameriflux} and Falge et al.), and not extracted from global maps
- Koeppen-Geiger climate zone, to extract from global map by Beck et al. (file contained in {ingestr}, see [here](https://github.com/geco-bern/ingestr/blob/master/data-raw/koeppen_geiger/koeppen-geiger.tif))
- Complement missing information on elevation using ETOPO1
- Revise start and end year based on available data (and not file name)

We will need more info for the following points. Ask Yanghui Kang (yanghuikang@berkeley.edu) and Trevor Keenan (trevorkeenan@berkeley.edu). They collected more. What do they have? We definitely need:

- Presence of C4 grasses (logical)

**Comment by khufkens** [comment]
- Add script to clean up meta-data
- don't run whole routine again
- ..

**Comment by stineb** [comment]
Resolved by https://github.com/geco-bern/FluxDataKit/pull/72
