### ISSUE TITLE
Negative atmospheric pressure

### ISSUE THREAD

**Issue by FrancescoGrossi-unimi** [geco-bern/FluxDataKit#70]
The following sites have negative patm value: "BE-Bra" "DE-RuS" "DE-RuW" "BE-Lcr" "BE-Maa" "DE-Geb" "DE-Gri" "DE-Kli" "DE-Tha" "IT-MBo" "IT-Tor" "CZ-Lnz" "CH-Dav" "FI-Sii" "SE-Htm" "FI-Ken" "FR-FBn" "IT-SR2" "GF-Guy" "FI-Hyy" "FR-LGt" "GL-Dsk"

**Comment by stineb** [comment]
Make sure to treat -9999 as a missing value (`NA`). Does it solve the problem?

**Comment by FrancescoGrossi-unimi** [comment]
yes
