### ISSUE TITLE
Document MODIS QC flags

### ISSUE THREAD

**Issue by stineb** [geco-bern/FluxDataKit#77]
The following code is used to select only good-quality data:

```r
  # Use only good quality data
  # Random bit integer format, ask Martin if need to work these out again...
  qc_flags <- c(0, 2, 24, 26, 32, 34, 56, 58)

  df_modis <- df_modis |>
    filter(
      qc %in% qc_flags,
      ...
    ) |>
   ...
```

What do these numbers mean in terms of corresponding codes in MODIS product documentation?
@khufkens

**Comment by khufkens** [comment]
Ask Anna Ukkola, not my code, this has been kept on parity with PLUMBER2

https://github.com/aukkola/PLUMBER2/blob/93885013c48d4ae59f933fb253e9aa9ed8fad1fe/Step2_Process_MODIS_LAI_for_all_sites.R#L52
