### ISSUE TITLE
Trim MODIS data

### ISSUE THREAD

**Issue by stineb** [geco-bern/FluxDataKit#80]
Trim MODIS data to period covered by the data product MCD15A2H v006, see [here](https://lpdaac.usgs.gov/products/mcd15a2hv006/).

Info on data product:
```
Temporal Extent: 2002-07-04 to 2023-02-17
```

Should this be implemented for rsofun drivers only or also for LSM and FLUXNET-formatted files? What do you suggest @khufkens ?

**Comment by khufkens** [comment]
Data queried should support arbitrary lengths up until fairly recent, as per ORNL MODIS subset data support:
https://modis.ornl.gov/documentation.html

I.e. the current version of the fAPAR/LAI product is v061 (or v6.1) not v6!

How much data you include is an executive decision, it makes sense to end on a full / half year basis.

**Comment by stineb** [comment]
You write 'Data queried should support arbitrary lengths'. The issue here is not the query, but the treatment in FDK, which extends downloaded time series (which start earliest in 2002) to pre-2002 years by adding a mean seasonal cycle. I would prefer to only fill gaps after 2002 with the mean seasonal cycle, by not extend to years before. If the user wants to do this, it should be their own choice. Unless your intention was to have this equivalent some other workflow (e.g., PLUMBER)?

**Comment by stineb** [comment]
Ok, so I keep the [warning on the website](https://geco-bern.github.io/FluxDataKit/articles/01_setup.html#remote-sensing-data):

_WARNING: The MODIS product MCD15A2H v006 is available only from 2002-07-04 to 2023-02-17. In FluxDataKit, MODIS FPAR/LAI data is extended by a mean seasonal cycle to match the flux data coverage. To retain only original MODIS data from the period covered by the data product, remove data based on the dates on your own._

... and do not modify the dataset v3.
